apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-prod
  hostPath:
    path: /mnt/data/prod