kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-prod
  namespace: prod
spec:
  storageClassName: pv-prod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
